.TH "unix2dos" "1" "unix2dos 5.0" "2010" ""

.SH "NAME"

unix2dos \- UNIX to DOS/MAC text file format converter

.SH "SYNOPSYS"

unix2dos [options] [\-c convmode] [\-o file ...] [\-n infile outfile ...]
.PP
Options:
.PP
[\-fhkLlqV] [\-\-force] [\-\-help] [\-\-keepdate] [\-\-license] [\-\-newline] [\-\-quiet] [\-\-version]

.SH "DESCRIPTION"

.PP
Unix2dos converts text files in UNIX format to DOS/MAC format.
Binary files and non-regular files, such as soft links,
are automatically skipped, unless conversion is forced.

Unix2dos has a few conversion modes similar to unix2dos under SunOS/Solaris.

In DOS/Windows text files line endings exist out of a combination of two characters:
a Carriage Return (CR) followed by a Line Feed (LF).
In Unix text files line endings exists out of a single Newline character which
is equal to a DOS Line Feed (LF) character.
In Mac text files, prior to Mac OS X, line endings exist out of a single Carriage
Return character. Mac OS X is Unix based and has the same line endings as Unix.

.SH "OPTIONS"
The following options are available:

.TP
.B \-c \-\-convmode convmode
Set conversion mode. Where convmode is one of:
.B ascii, 7bit, iso, mac
with ascii being the default.

.TP
.B \-f \-\-force
Force conversion of all files. Also binary files.

.TP
.B \-h \-\-help
Display online help.

.TP
.B \-k \-\-keepdate
Keep the date stamp of output file same as input file.

.TP
.B \-L \-\-license
Display software license.

.TP
.B \-l \-\-newline
Add additional newline.
Only Unix line endings are changed to two DOS line endings.
In Mac mode Unix line endings are changed to two Mac line endings.

.TP
.B \-n \-\-newfile infile outfile ...
New file mode. Convert the infile and write output to outfile. File names
must be given in pairs and wildcard names should NOT be used or you WILL
lose your files.

.TP
.B \-o \-\-oldfile file ...
Old file mode. Convert the file and write output to it. The program
default to run in this mode. Wildcard names may be used.

.TP
.B \-q \-\-quiet
Quiet mode. Suppress all warning and messages.

.TP
.B \-V \-\-version
Display version information.

.SH "CONVERSION MODES"

Conversion modes
.B ascii
,
.B 7bit
, and
.B iso
are similar to those of unix2dos under SunOS/Solaris.

.TP
.B ascii
In this mode Unix line endings are converted to DOS line endings.
DOS and Mac line endings are not changed.

Although the name of this mode is ASCII, which is a 7 bit standard,
the actual mode is 8 bit.

.TP
.B mac
In this mode Unix line endings are converted to Mac line endings.
DOS and Mac line endigs are not changed.

.TP
.B 7bit
In this mode Unix line endings are converted to DOS line endings.
All 8 bit non-ASCII characters (with values from 128 to 255) are converted
to a space.

.TP
.B iso
In this mode Unix line endings are converted to DOS line endings.  Characters
are converted from ISO character set ISO-8859-1 to DOS character set (code
page) CP437. ISO-8859-1 characters without CP437 equivalent, for which
conversion is not possible, are converted to a dot.  CP437 is mainly used in
the USA. In Western Europe CP850 is more standard.

Another option to convert text files between different encodings is to use
unix2dos in combination with iconv(1). Iconv can convert between a long list of
character encodings. Some examples:

Convert from Unix Latin-1 to DOS DOSLatinUS
.IP
.B unix2dos < in.txt | iconv \-f ISO-8859-1 \-t CP437 > out.txt

Convert from Unix Latin-1 to DOS DOSLatin1
.IP
.B unix2dos < in.txt | iconv \-f ISO-8859-1 \-t CP850 > out.txt

Convert from Unix Latin-1 to Windows WinLatin1
.IP
.B unix2dos < in.txt | iconv \-f ISO-8859-1 \-t CP1252 > out.txt

Convert from Unix UTF-8 (Unicode) to Windows WinLatin1
.IP
.B unix2dos < in.txt | iconv \-f UTF-8 \-t CP1252 in.txt > out.txt

Convert from Unix UTF-8 (Unicode) to Windows UTF-16 (Unicode)
.IP
.B unix2dos < in.txt | iconv \-f UTF-8 \-t UTF-16 > out.txt

See also <http://czyborra.com/charsets/codepages.html>
.br
and <http://czyborra.com/charsets/iso8859.html>.

.SH "UNICODE"

Unicode files can be encoded in different encodings. On Unix/Linux Unicode
files are mostly encoded in UTF-8 encoding. UTF-8 is ASCII compatible. UTF-8
files can be in DOS, Unix or Mac format. It is safe to run dos2unix/unix2dos on
UTF-8 encoded files. On Windows mostly UTF-16 encoding is used for Unicode
files. Dos2unix/unix2dos should not be run on UTF-16 files. UTF-16 files are
automatically skipped, because it are binary files.

.SH "EXAMPLES"
.LP
Get input from stdin and write output to stdout.
.IP
.B unix2dos

.LP
Convert and replace a.txt. Convert and replace b.txt.
.IP
.B unix2dos a.txt b.txt
.IP
.B unix2dos \-o a.txt b.txt

.LP
Convert and replace a.txt in ascii conversion mode.
Convert and replace b.txt in 7bit conversion mode.
.IP
.B unix2dos a.txt \-c 7bit b.txt
.IP
.B unix2dos \-c ascii a.txt \-c 7bit b.txt

.LP
Convert a.txt from Unix to Mac format.
.IP 
.B dos2unix \-c mac a.txt
.IP 
.B unix2mac a.txt

.LP 
Convert and replace a.txt while keeping original date stamp.
.IP
.B unix2dos \-k a.txt
.IP
.B unix2dos \-k \-o a.txt

.LP
Convert a.txt and write to e.txt.
.IP
.B unix2dos \-n a.txt e.txt

.LP
Convert a.txt and write to e.txt, keep date stamp of e.txt same as a.txt.
.IP
.B unix2dos \-k \-n a.txt e.txt 

.LP
Convert and replace a.txt. Convert b.txt and write to e.txt.
.IP
.B unix2dos a.txt \-n b.txt e.txt
.IP
.B unix2dos \-o a.txt \-n b.txt e.txt

.LP
Convert c.txt and write to e.txt. Convert and replace a.txt.
Convert and replace b.txt. Convert d.txt and write to f.txt.
.IP
.B unix2dos \-n c.txt e.txt \-o a.txt b.txt \-n d.txt f.txt

.SH "AUTHORS"

Benjamin Lin \- <blin@socs.uts.edu.au>

Erwin Waterlander \- <waterlan@xs4all.nl>

Project page: http://www.xs4all.nl/~waterlan/dos2unix.html

SourceForge page: http://sourceforge.net/projects/dos2unix/

Freshmeat: http://freshmeat.net/projects/dos2unix

.SH "SEE ALSO"
dos2unix(1) unix2mac(1) iconv(1)

